### PR TITLE
Two cosmetic fixes

### PR DESCRIPTION
**Pull request by lkundrak**
Should not change functionality (not tested, since I don't have a SSTP server set up). The former one makes GNOME Software happier; the other makes one a better person in the eyes of Thomas (of the NetworkManager crowd).

### CODE REVIEW

**Comment by enaess** [comment]
Thanks, I am in the midst of porting the reminder of the changes from the pptp client. I'll look these over and hand merge them. You could try to connect to ca.freesstpvpn.com user:vpn, pass: freesstp. If that doesn't work, they may have a different access point, just Google freesstpvpn 
I expect to have the changes done by the weekend.
Regards,Eivind 


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by enaess** [comment]
Hi Lubomir!
Are you able to have a second look at the nm-sstp-service.c file, there's some conflicts and am not sure how to merge these (or if these are even needed now as I took most of the recent changes from network-manager-pptp). 

Regards,

**Comment by enaess** [comment]
@lkundrak Do you have an update for me? Is the merge for nm-sstp-service.c still needed?

**Comment by lkundrak** [comment]
Ouch; 581bb16af (Adding in recent changes from the network-manager-pptp project to keep the projects similar) does not look good.

For the service you actually reverted the changes that were done to the service. Introducing back broken stuff (such as the separate ppp bus service) that was fixed in both pptp and sstp :(

Perhaps you diffed against a wrong version?

**Comment by enaess** [comment]
@lkundrak 
You are probably right, what branch / tag version should I be using instead? 

- Eivind

**Comment by lkundrak** [comment]
master

**Comment by enaess** [comment]
@lkundrak I merged the changes from mainline. Looks like ubuntu is on the NM 1.2 release in which doesn't have all the changes in master (and I am not able to call the new dbus interface for VPN). I created a release-1.2 branch for this prior to committing the merge from pptp to master.

**Comment by enaess** [comment]
I am going to close this merge request, I think it's served it purpose.

**Comment by lkundrak** [comment]
It indeed looks good to me now. Thanks!

I'm wondering if you could tag a release? That would make things easier for packagers.

**Pull request closed without merging**
